name: SHENYU-ACTION
on: 
  push:
    branches:
      - 'v*.*'

jobs:
  scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3         
 
    - name: Send Notification-Right
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: Image build and signed
        SLACK_MESSAGE: |
          Name:SHEN YU
          Metricculation:A0286012M
          Email:<https://outlook.office365.com/mail/ | E1221824@u.nus.edu>
          Git:<https://github.com/${{ github.repository }}| Github repository of CICD>
          Image:<https://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general | https://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general>