name: SHENYU-ACTION
on: 
  push:
    branches:
      - 'v*.*'

jobs:
  scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3                  
    
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH'
    
    


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:          
        registry: lukelukeyuy/shenyu-cicd
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: lukelukeyuy/shenyu-cicd/v12345
        tags: type=sha,format=hash
         
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}

    - name: Sign image with a key
      run: |
        cosign sign --key -yes env://COSIGN_PRIVATE_KEY "${TAGS}"
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        TAGS: ${{ steps.docker_meta.outputs.tags }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
    
    - name: Send Notification-Right
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: Image build and signed
        SLACK_MESSAGE: |
          Name:SHEN YU
          Metricculation:E1221824
          Email:<mailtohttps://outlook.office365.com/mail/ | E1221824@u.nus.edu>
          Git:<mailtohttps://github.com/lukewwwwww/CICD-ShenYu | Github repository of CICD>
          Image:<mailtohttps://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general | https://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general>
