name: 1
on: [push]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Send Notification
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_TITLE: CICD-PROJECT
          SLACK_MESSAGE: |
            Name:SHEN YU
            Email:<mailtoE1221824@u.nus.edu|E1221824@u.nus.edu>

