name: SHENYU-ACTION
on: 
  push:
    branches:
      - 'v*.*'

jobs:
  scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3                  
    
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH'
    


    - id: commithash
      uses: prompt/actions-commit-hash@v3
      
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        push: true
        tags: 'lukelukeyuy/shenyu-cicd:${{ steps.commithash.outputs.hash }}'

    - name: Sign image with a key
      run: |
        cosign sign -yes --key ${{ secrets.COSIGN_PRIVATE_KEY }} lukelukeyuy/shenyu-cicd:${{ steps.commithash.outputs.hash }}
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    
    - name: Send Notification-Right
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: Image build and signed
        SLACK_MESSAGE: |
          Name:SHEN YU
          Metricculation:E1221824
          Email:<mailtohttps://outlook.office365.com/mail/ | E1221824@u.nus.edu>
          Git:<mailtohttps://github.com/lukewwwwww/CICD-ShenYu | Github repository of CICD>
          Image:<mailtohttps://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general | https://hub.docker.com/repository/docker/lukelukeyuy/shenyu-cicd/general>
