name: SHENYU-ACTION
on: 
  push:
    branches:
      - 'v*.*'

jobs:
  scan:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3                  
    
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH'

  

    - name: Checkout code
      uses: actions/checkout@v3

    - id: commithash
      uses: prompt/actions-commit-hash@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}



    - name: Build and push
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        push: true
        tags: ${{ steps.commithash.outputs.short }}

    - name: Sign image with a key
      run: |
        cosign sign --key  "${{ secrets.COSIGN_PRIVATE_KEY }}" -y <lukelukeyuy/shenyu-cicd:v1234>
        cosign verify --key '../../cosign.pub' <lukelukeyuy/shenyu-cicd:v1234>
      env:
        TAGS: ${{ steps.docker_meta.outputs.tags }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
