name: 1
on: [push]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Send Notification
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_TITLE: CICD-PROJECT
          SLACK_MESSAGE: |
            Name:SHEN YU
            Metricculation:E1221824
            Email:<mailtohttps://outlook.office365.com/mail/ | E1221824@u.nus.edu>
            Git:<mailtohttps://github.com/lukewwwwww/CICD-ShenYu | Github repository of CICD>
            Image:
